export const getProfileBaseStyles = (theme) => ({
  screen: {
    flex: 1,
    backgroundColor: theme.colors.dashboardBg,
  },
  keyboardWrap: {
    flex: 1,
  },
  headerBar: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.onPrimarySoft,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.onPrimarySoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 20,
    fontWeight: "800",
    color: theme.colors.onPrimary,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 32,
    gap: 18,
  },
  heroCard: {
    backgroundColor: theme.colors.primary,
    borderRadius: 24,
    padding: 18,
    overflow: "hidden",
    ...theme.shadow.card,
  },
  heroAccent: {
    width: 56,
    height: 6,
    borderRadius: 999,
    backgroundColor: theme.colors.onPrimary,
    opacity: 0.7,
    marginBottom: 10,
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: theme.colors.onPrimary,
  },
  heroSubtitle: {
    fontSize: 12,
    marginTop: 6,
    color: theme.colors.onPrimaryMuted,
  },
  card: {
    backgroundColor: theme.colors.background,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...theme.shadow.card,
  },
});
