const admin = require("firebase-admin");
const serviceAccount = require("./serviceAccountKey.json");

admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
const db = admin.firestore();

const seedData = async () => {
  const deals = [
    {
      title: "50% Off Pizza Combo",
      description: "Buy pizza combo at half price when group completes",
      category: "Food",
      price: 499,
      discountPrice: 499,
      originalPrice: 999,
      minGroupSize: 5,
      minThreshold: 5,
      joinedUsers: 2,
      currentJoins: 2,
      location: "Bangalore",
      expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
      expiryTime: new Date(Date.now() + 24 * 60 * 60 * 1000),
      status: "active",
      lifecycleStatus: "active",
      approvalStatus: "approved",
      approved: true,
      sellerId: "vendor_001",
      viewsCount: 0,
      favoritesCount: 0,
      leftCount: 0,
      joinEventsCount: 0,
      avgJoinTimeSeconds: null,
      thresholdReachedAt: null,
      ratingCount: 0,
      ratingTotal: 0,
      ratingAvg: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "iPhone Accessories Deal",
      description: "Group deal on premium iPhone accessories",
      category: "Electronics",
      price: 1999,
      discountPrice: 1999,
      originalPrice: 2999,
      minGroupSize: 10,
      minThreshold: 10,
      joinedUsers: 4,
      currentJoins: 4,
      location: "Mumbai",
      expiresAt: new Date(Date.now() + 48 * 60 * 60 * 1000),
      expiryTime: new Date(Date.now() + 48 * 60 * 60 * 1000),
      status: "active",
      lifecycleStatus: "active",
      approvalStatus: "approved",
      approved: true,
      sellerId: "vendor_002",
      viewsCount: 0,
      favoritesCount: 0,
      leftCount: 0,
      joinEventsCount: 0,
      avgJoinTimeSeconds: null,
      thresholdReachedAt: null,
      ratingCount: 0,
      ratingTotal: 0,
      ratingAvg: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Fashion Clearance Sale",
      description: "Group deal on branded clothing",
      category: "Fashion",
      price: 1499,
      discountPrice: 1499,
      originalPrice: 2499,
      minGroupSize: 8,
      minThreshold: 8,
      joinedUsers: 1,
      currentJoins: 1,
      location: "Delhi",
      expiresAt: new Date(Date.now() + 72 * 60 * 60 * 1000),
      expiryTime: new Date(Date.now() + 72 * 60 * 60 * 1000),
      status: "active",
      lifecycleStatus: "active",
      approvalStatus: "approved",
      approved: true,
      sellerId: "vendor_003",
      viewsCount: 0,
      favoritesCount: 0,
      leftCount: 0,
      joinEventsCount: 0,
      avgJoinTimeSeconds: null,
      thresholdReachedAt: null,
      ratingCount: 0,
      ratingTotal: 0,
      ratingAvg: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  for (const deal of deals) {
    await db.collection("deals").add(deal);
  }
  console.log("Database Seeded!");
  process.exit();
};

seedData();
