const DEALS_COLLECTION = "deals";
const USERS_COLLECTION = "users";
const DEAL_JOINS_COLLECTION = "dealJoins";
const PAYMENTS_COLLECTION = "payments";
const PAYMENT_EVENTS_COLLECTION = "paymentEvents";
const REVIEWS_COLLECTION = "reviews";
const NOTIFICATIONS_COLLECTION = "notifications";
const ADDRESS_COLLECTION = "addresses";

const DEFAULT_DEAL_LIMIT = 200;
const MAX_DEAL_LIMIT = 1000;
const DEFAULT_ADDRESS_COUNTRY = "India";

module.exports = {
  DEALS_COLLECTION,
  USERS_COLLECTION,
  DEAL_JOINS_COLLECTION,
  PAYMENTS_COLLECTION,
  PAYMENT_EVENTS_COLLECTION,
  REVIEWS_COLLECTION,
  NOTIFICATIONS_COLLECTION,
  ADDRESS_COLLECTION,
  DEFAULT_DEAL_LIMIT,
  MAX_DEAL_LIMIT,
  DEFAULT_ADDRESS_COUNTRY,
};
