// Notification wording per language. pushNotification() (lib.js) renders a
// { key, vars } message into the recipient's users/{uid}.preferredLanguage
// at send time - the in-app list and the OS push both show that text.
// Missing language/key falls back to English. {{title}} is the deal title,
// already translated by the caller path (see renderNotification).
//
// All non-English wording here and in packages/shared/i18n/locales should
// be reviewed by native speakers before launch.
const { translateDealText, normalizeLanguage } = require("./translation");

// Notifications can afford a longer wait than a list request - they're sent
// in the background of a request, and an untranslated title can't be fixed
// after the push has gone out.
const NOTIFICATION_TRANSLATION_WAIT_MS = 4000;

const TEMPLATES = {
  en: {
    someBuyer: "A buyer",
    yourDeal: "your deal",
    dealExpiredShortfall: { title: "Deal expired", body: '"{{title}}" expired before all buyers completed payment. It has moved to Expired.' },
    dealExpiredQuorum: { title: "Deal expired", body: '"{{title}}" expired without reaching enough buyers. It has moved to Expired.' },
    refundedExpired: { title: "Payment refunded", body: 'Your held payment for "{{title}}" has been released back to you because the deal expired.' },
    accountApprovedSeller: { title: "Account approved", body: "Your seller account is approved." },
    accountApproved: { title: "Account approved", body: "Your account is approved." },
    accountRejected: { title: "Account rejected", body: "Your account request was rejected by admin." },
    accountRejectedReason: { title: "Account rejected", body: "{{reason}}" },
    dealApproved: { title: "Deal approved", body: "{{title}}" },
    dealRejected: { title: "Deal rejected", body: "Your deal was rejected by admin" },
    dealRejectedReason: { title: "Deal rejected", body: "{{reason}}" },
    newDeal: { title: "New deal published", body: "{{title}}" },
    chatMessage: { title: "New message · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "Payment received", body: '{{buyer}} paid for "{{title}}". Payment is held until delivery is confirmed.' },
    dealCompleted: { title: "Deal completed", body: 'The seller marked "{{title}}" as completed. It will be dispatched shortly.' },
    priceDropped: { title: "Price dropped!", body: 'More buyers joined "{{title}}" - ₹{{amount}} has been refunded to you as the group price dropped.' },
    dealEndedBySeller: { title: "Deal ended", body: '"{{title}}" was ended by the seller before reaching enough buyers.' },
    refunded: { title: "Payment refunded", body: 'Your held payment for "{{title}}" has been released back to you.' },
    dispatched: { title: "Your order is on the way!", body: "{{title}} has been dispatched. Open the app to view your delivery confirmation code." },
    deliveryConfirmed: { title: "Delivery confirmed", body: "{{buyer}} confirmed delivery for {{title}}." },
    allDelivered: { title: "All orders delivered", body: "Every joined buyer has confirmed delivery for {{title}}." },
    pickupConfirmed: { title: "Pickup confirmed", body: 'Your pickup for "{{title}}" has been confirmed by the seller.' },
    deliveryMarkedBySeller: { title: "Delivery marked complete", body: 'The seller marked your order for "{{title}}" as delivered.' },
  },
  hi: {
    someBuyer: "एक खरीदार",
    yourDeal: "आपकी डील",
    dealExpiredShortfall: { title: "डील समाप्त", body: '"{{title}}" सभी खरीदारों के भुगतान से पहले समाप्त हो गई। इसे समाप्त में भेज दिया गया है।' },
    dealExpiredQuorum: { title: "डील समाप्त", body: '"{{title}}" ज़रूरी खरीदारों तक पहुँचे बिना समाप्त हो गई। इसे समाप्त में भेज दिया गया है।' },
    refundedExpired: { title: "भुगतान वापस", body: '"{{title}}" के लिए रोका गया आपका भुगतान डील समाप्त होने के कारण आपको वापस कर दिया गया है।' },
    accountApprovedSeller: { title: "खाता मंज़ूर", body: "आपका विक्रेता खाता मंज़ूर हो गया है।" },
    accountApproved: { title: "खाता मंज़ूर", body: "आपका खाता मंज़ूर हो गया है।" },
    accountRejected: { title: "खाता अस्वीकृत", body: "एडमिन ने आपका खाता अनुरोध अस्वीकार कर दिया।" },
    accountRejectedReason: { title: "खाता अस्वीकृत", body: "{{reason}}" },
    dealApproved: { title: "डील मंज़ूर", body: "{{title}}" },
    dealRejected: { title: "डील अस्वीकृत", body: "एडमिन ने आपकी डील अस्वीकार कर दी" },
    dealRejectedReason: { title: "डील अस्वीकृत", body: "{{reason}}" },
    newDeal: { title: "नई डील प्रकाशित हुई", body: "{{title}}" },
    chatMessage: { title: "नया संदेश · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "भुगतान मिला", body: '{{buyer}} ने "{{title}}" के लिए भुगतान किया। डिलीवरी पक्की होने तक भुगतान रोका गया है।' },
    dealCompleted: { title: "डील पूरी हुई", body: 'विक्रेता ने "{{title}}" को पूरा बताया है। इसे जल्द भेजा जाएगा।' },
    priceDropped: { title: "कीमत घटी!", body: '"{{title}}" में और खरीदार जुड़े - ग्रुप कीमत घटने से ₹{{amount}} आपको वापस किए गए हैं।' },
    dealEndedBySeller: { title: "डील बंद हुई", body: 'विक्रेता ने "{{title}}" को ज़रूरी खरीदार पूरे होने से पहले बंद कर दिया।' },
    refunded: { title: "भुगतान वापस", body: '"{{title}}" के लिए रोका गया आपका भुगतान आपको वापस कर दिया गया है।' },
    dispatched: { title: "आपका ऑर्डर रास्ते में है!", body: "{{title}} भेज दी गई है। डिलीवरी पुष्टि कोड देखने के लिए ऐप खोलें।" },
    deliveryConfirmed: { title: "डिलीवरी पक्की", body: "{{buyer}} ने {{title}} की डिलीवरी पक्की की।" },
    allDelivered: { title: "सभी ऑर्डर डिलीवर", body: "{{title}} से जुड़े सभी खरीदारों ने डिलीवरी पक्की कर दी है।" },
    pickupConfirmed: { title: "पिकअप पक्का", body: 'विक्रेता ने "{{title}}" का आपका पिकअप पक्का कर दिया है।' },
    deliveryMarkedBySeller: { title: "डिलीवरी पूरी बताई गई", body: 'विक्रेता ने "{{title}}" का आपका ऑर्डर डिलीवर बताया है।' },
  },
  mr: {
    someBuyer: "एक खरेदीदार",
    yourDeal: "तुमची डील",
    dealExpiredShortfall: { title: "डील संपली", body: '"{{title}}" सर्व खरेदीदारांनी पैसे भरण्यापूर्वीच संपली. ती संपलेल्या डीलमध्ये हलवली आहे.' },
    dealExpiredQuorum: { title: "डील संपली", body: '"{{title}}" पुरेसे खरेदीदार न मिळता संपली. ती संपलेल्या डीलमध्ये हलवली आहे.' },
    refundedExpired: { title: "पैसे परत", body: 'डील संपल्यामुळे "{{title}}" साठी राखून ठेवलेले तुमचे पैसे तुम्हाला परत केले आहेत.' },
    accountApprovedSeller: { title: "खाते मंजूर", body: "तुमचे विक्रेता खाते मंजूर झाले आहे." },
    accountApproved: { title: "खाते मंजूर", body: "तुमचे खाते मंजूर झाले आहे." },
    accountRejected: { title: "खाते नाकारले", body: "ॲडमिनने तुमची खाते विनंती नाकारली." },
    accountRejectedReason: { title: "खाते नाकारले", body: "{{reason}}" },
    dealApproved: { title: "डील मंजूर", body: "{{title}}" },
    dealRejected: { title: "डील नाकारली", body: "ॲडमिनने तुमची डील नाकारली" },
    dealRejectedReason: { title: "डील नाकारली", body: "{{reason}}" },
    newDeal: { title: "नवीन डील प्रकाशित", body: "{{title}}" },
    chatMessage: { title: "नवीन संदेश · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "पैसे मिळाले", body: '{{buyer}} यांनी "{{title}}" साठी पैसे भरले. डिलिव्हरी निश्चित होईपर्यंत पैसे राखून ठेवले आहेत.' },
    dealCompleted: { title: "डील पूर्ण", body: 'विक्रेत्याने "{{title}}" पूर्ण झाल्याचे नोंदवले. ती लवकरच पाठवली जाईल.' },
    priceDropped: { title: "किंमत कमी झाली!", body: '"{{title}}" मध्ये आणखी खरेदीदार सामील झाले - गट किंमत कमी झाल्याने ₹{{amount}} तुम्हाला परत केले आहेत.' },
    dealEndedBySeller: { title: "डील बंद झाली", body: 'पुरेसे खरेदीदार मिळण्यापूर्वी विक्रेत्याने "{{title}}" बंद केली.' },
    refunded: { title: "पैसे परत", body: '"{{title}}" साठी राखून ठेवलेले तुमचे पैसे तुम्हाला परत केले आहेत.' },
    dispatched: { title: "तुमची ऑर्डर मार्गावर आहे!", body: "{{title}} पाठवली आहे. डिलिव्हरी पुष्टी कोड पाहण्यासाठी ॲप उघडा." },
    deliveryConfirmed: { title: "डिलिव्हरी निश्चित", body: "{{buyer}} यांनी {{title}} ची डिलिव्हरी निश्चित केली." },
    allDelivered: { title: "सर्व ऑर्डर पोहोचल्या", body: "{{title}} मधील सर्व खरेदीदारांनी डिलिव्हरी निश्चित केली आहे." },
    pickupConfirmed: { title: "पिकअप निश्चित", body: 'विक्रेत्याने "{{title}}" चा तुमचा पिकअप निश्चित केला आहे.' },
    deliveryMarkedBySeller: { title: "डिलिव्हरी पूर्ण नोंदवली", body: 'विक्रेत्याने "{{title}}" ची तुमची ऑर्डर पोहोचल्याचे नोंदवले.' },
  },
  ta: {
    someBuyer: "ஒரு வாங்குபவர்",
    yourDeal: "உங்கள் டீல்",
    dealExpiredShortfall: { title: "டீல் காலாவதியானது", body: '"{{title}}" அனைத்து வாங்குபவர்களும் பணம் செலுத்தும் முன் காலாவதியானது. இது காலாவதியானவை பகுதிக்கு மாற்றப்பட்டது.' },
    dealExpiredQuorum: { title: "டீல் காலாவதியானது", body: '"{{title}}" போதுமான வாங்குபவர்கள் இல்லாமல் காலாவதியானது. இது காலாவதியானவை பகுதிக்கு மாற்றப்பட்டது.' },
    refundedExpired: { title: "பணம் திருப்பி அளிக்கப்பட்டது", body: 'டீல் காலாவதியானதால் "{{title}}"-க்கு நிறுத்தி வைக்கப்பட்ட உங்கள் பணம் திருப்பி அளிக்கப்பட்டது.' },
    accountApprovedSeller: { title: "கணக்கு அங்கீகரிக்கப்பட்டது", body: "உங்கள் விற்பனையாளர் கணக்கு அங்கீகரிக்கப்பட்டது." },
    accountApproved: { title: "கணக்கு அங்கீகரிக்கப்பட்டது", body: "உங்கள் கணக்கு அங்கீகரிக்கப்பட்டது." },
    accountRejected: { title: "கணக்கு நிராகரிக்கப்பட்டது", body: "உங்கள் கணக்கு கோரிக்கையை நிர்வாகி நிராகரித்தார்." },
    accountRejectedReason: { title: "கணக்கு நிராகரிக்கப்பட்டது", body: "{{reason}}" },
    dealApproved: { title: "டீல் அங்கீகரிக்கப்பட்டது", body: "{{title}}" },
    dealRejected: { title: "டீல் நிராகரிக்கப்பட்டது", body: "உங்கள் டீலை நிர்வாகி நிராகரித்தார்" },
    dealRejectedReason: { title: "டீல் நிராகரிக்கப்பட்டது", body: "{{reason}}" },
    newDeal: { title: "புதிய டீல் வெளியிடப்பட்டது", body: "{{title}}" },
    chatMessage: { title: "புதிய செய்தி · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "பணம் பெறப்பட்டது", body: '{{buyer}} "{{title}}"-க்கு பணம் செலுத்தினார். டெலிவரி உறுதியாகும் வரை பணம் நிறுத்தி வைக்கப்படும்.' },
    dealCompleted: { title: "டீல் முடிந்தது", body: 'விற்பனையாளர் "{{title}}" முடிந்ததாக குறித்துள்ளார். விரைவில் அனுப்பப்படும்.' },
    priceDropped: { title: "விலை குறைந்தது!", body: '"{{title}}"-இல் மேலும் வாங்குபவர்கள் சேர்ந்தனர் - குழு விலை குறைந்ததால் ₹{{amount}} உங்களுக்கு திருப்பி அளிக்கப்பட்டது.' },
    dealEndedBySeller: { title: "டீல் முடிக்கப்பட்டது", body: 'போதுமான வாங்குபவர்கள் சேரும் முன் விற்பனையாளர் "{{title}}"-ஐ முடித்தார்.' },
    refunded: { title: "பணம் திருப்பி அளிக்கப்பட்டது", body: '"{{title}}"-க்கு நிறுத்தி வைக்கப்பட்ட உங்கள் பணம் திருப்பி அளிக்கப்பட்டது.' },
    dispatched: { title: "உங்கள் ஆர்டர் வழியில் உள்ளது!", body: "{{title}} அனுப்பப்பட்டது. டெலிவரி உறுதிப்படுத்தல் குறியீட்டைக் காண ஆப்பைத் திறக்கவும்." },
    deliveryConfirmed: { title: "டெலிவரி உறுதிசெய்யப்பட்டது", body: "{{buyer}} {{title}}-இன் டெலிவரியை உறுதிசெய்தார்." },
    allDelivered: { title: "அனைத்து ஆர்டர்களும் டெலிவரி ஆனது", body: "{{title}}-இல் சேர்ந்த அனைத்து வாங்குபவர்களும் டெலிவரியை உறுதிசெய்தனர்." },
    pickupConfirmed: { title: "பிக்அப் உறுதிசெய்யப்பட்டது", body: '"{{title}}"-க்கான உங்கள் பிக்அப்பை விற்பனையாளர் உறுதிசெய்தார்.' },
    deliveryMarkedBySeller: { title: "டெலிவரி முடிந்ததாக குறிக்கப்பட்டது", body: '"{{title}}"-க்கான உங்கள் ஆர்டர் டெலிவரி ஆனதாக விற்பனையாளர் குறித்தார்.' },
  },
  te: {
    someBuyer: "ఒక కొనుగోలుదారు",
    yourDeal: "మీ డీల్",
    dealExpiredShortfall: { title: "డీల్ గడువు ముగిసింది", body: '"{{title}}" కొనుగోలుదారులందరూ చెల్లించక ముందే గడువు ముగిసింది. ఇది గడువు ముగిసినవి విభాగానికి మారింది.' },
    dealExpiredQuorum: { title: "డీల్ గడువు ముగిసింది", body: '"{{title}}" తగినంత మంది కొనుగోలుదారులు లేకుండానే గడువు ముగిసింది. ఇది గడువు ముగిసినవి విభాగానికి మారింది.' },
    refundedExpired: { title: "చెల్లింపు తిరిగి ఇవ్వబడింది", body: 'డీల్ గడువు ముగిసినందున "{{title}}" కోసం నిలిపి ఉంచిన మీ చెల్లింపు మీకు తిరిగి ఇవ్వబడింది.' },
    accountApprovedSeller: { title: "ఖాతా ఆమోదించబడింది", body: "మీ విక్రేత ఖాతా ఆమోదించబడింది." },
    accountApproved: { title: "ఖాతా ఆమోదించబడింది", body: "మీ ఖాతా ఆమోదించబడింది." },
    accountRejected: { title: "ఖాతా తిరస్కరించబడింది", body: "మీ ఖాతా అభ్యర్థనను అడ్మిన్ తిరస్కరించారు." },
    accountRejectedReason: { title: "ఖాతా తిరస్కరించబడింది", body: "{{reason}}" },
    dealApproved: { title: "డీల్ ఆమోదించబడింది", body: "{{title}}" },
    dealRejected: { title: "డీల్ తిరస్కరించబడింది", body: "మీ డీల్‌ను అడ్మిన్ తిరస్కరించారు" },
    dealRejectedReason: { title: "డీల్ తిరస్కరించబడింది", body: "{{reason}}" },
    newDeal: { title: "కొత్త డీల్ ప్రచురించబడింది", body: "{{title}}" },
    chatMessage: { title: "కొత్త సందేశం · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "చెల్లింపు అందింది", body: '{{buyer}} "{{title}}" కోసం చెల్లించారు. డెలివరీ నిర్ధారించే వరకు చెల్లింపు నిలిపి ఉంచబడుతుంది.' },
    dealCompleted: { title: "డీల్ పూర్తయింది", body: 'విక్రేత "{{title}}" పూర్తయినట్లు గుర్తించారు. త్వరలో పంపబడుతుంది.' },
    priceDropped: { title: "ధర తగ్గింది!", body: '"{{title}}"లో మరింత మంది కొనుగోలుదారులు చేరారు - గ్రూప్ ధర తగ్గినందున ₹{{amount}} మీకు తిరిగి ఇవ్వబడింది.' },
    dealEndedBySeller: { title: "డీల్ ముగిసింది", body: 'తగినంత మంది కొనుగోలుదారులు చేరక ముందే విక్రేత "{{title}}"ను ముగించారు.' },
    refunded: { title: "చెల్లింపు తిరిగి ఇవ్వబడింది", body: '"{{title}}" కోసం నిలిపి ఉంచిన మీ చెల్లింపు మీకు తిరిగి ఇవ్వబడింది.' },
    dispatched: { title: "మీ ఆర్డర్ దారిలో ఉంది!", body: "{{title}} పంపబడింది. డెలివరీ నిర్ధారణ కోడ్ చూడటానికి యాప్‌ను తెరవండి." },
    deliveryConfirmed: { title: "డెలివరీ నిర్ధారించబడింది", body: "{{buyer}} {{title}} డెలివరీని నిర్ధారించారు." },
    allDelivered: { title: "అన్ని ఆర్డర్లు డెలివరీ అయ్యాయి", body: "{{title}}లో చేరిన కొనుగోలుదారులందరూ డెలివరీని నిర్ధారించారు." },
    pickupConfirmed: { title: "పికప్ నిర్ధారించబడింది", body: '"{{title}}" కోసం మీ పికప్‌ను విక్రేత నిర్ధారించారు.' },
    deliveryMarkedBySeller: { title: "డెలివరీ పూర్తయినట్లు గుర్తించబడింది", body: '"{{title}}" కోసం మీ ఆర్డర్ డెలివరీ అయినట్లు విక్రేత గుర్తించారు.' },
  },
  kn: {
    someBuyer: "ಒಬ್ಬ ಖರೀದಿದಾರ",
    yourDeal: "ನಿಮ್ಮ ಡೀಲ್",
    dealExpiredShortfall: { title: "ಡೀಲ್ ಅವಧಿ ಮುಗಿದಿದೆ", body: '"{{title}}" ಎಲ್ಲಾ ಖರೀದಿದಾರರು ಪಾವತಿಸುವ ಮೊದಲೇ ಅವಧಿ ಮುಗಿದಿದೆ. ಇದನ್ನು ಅವಧಿ ಮುಗಿದವುಗಳಿಗೆ ಸರಿಸಲಾಗಿದೆ.' },
    dealExpiredQuorum: { title: "ಡೀಲ್ ಅವಧಿ ಮುಗಿದಿದೆ", body: '"{{title}}" ಸಾಕಷ್ಟು ಖರೀದಿದಾರರಿಲ್ಲದೆ ಅವಧಿ ಮುಗಿದಿದೆ. ಇದನ್ನು ಅವಧಿ ಮುಗಿದವುಗಳಿಗೆ ಸರಿಸಲಾಗಿದೆ.' },
    refundedExpired: { title: "ಪಾವತಿ ಹಿಂತಿರುಗಿಸಲಾಗಿದೆ", body: 'ಡೀಲ್ ಅವಧಿ ಮುಗಿದಿದ್ದರಿಂದ "{{title}}"ಗಾಗಿ ತಡೆಹಿಡಿದ ನಿಮ್ಮ ಪಾವತಿಯನ್ನು ನಿಮಗೆ ಹಿಂತಿರುಗಿಸಲಾಗಿದೆ.' },
    accountApprovedSeller: { title: "ಖಾತೆ ಅನುಮೋದಿಸಲಾಗಿದೆ", body: "ನಿಮ್ಮ ಮಾರಾಟಗಾರ ಖಾತೆ ಅನುಮೋದಿಸಲಾಗಿದೆ." },
    accountApproved: { title: "ಖಾತೆ ಅನುಮೋದಿಸಲಾಗಿದೆ", body: "ನಿಮ್ಮ ಖಾತೆ ಅನುಮೋದಿಸಲಾಗಿದೆ." },
    accountRejected: { title: "ಖಾತೆ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ", body: "ನಿಮ್ಮ ಖಾತೆ ವಿನಂತಿಯನ್ನು ಅಡ್ಮಿನ್ ತಿರಸ್ಕರಿಸಿದ್ದಾರೆ." },
    accountRejectedReason: { title: "ಖಾತೆ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ", body: "{{reason}}" },
    dealApproved: { title: "ಡೀಲ್ ಅನುಮೋದಿಸಲಾಗಿದೆ", body: "{{title}}" },
    dealRejected: { title: "ಡೀಲ್ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ", body: "ನಿಮ್ಮ ಡೀಲ್ ಅನ್ನು ಅಡ್ಮಿನ್ ತಿರಸ್ಕರಿಸಿದ್ದಾರೆ" },
    dealRejectedReason: { title: "ಡೀಲ್ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ", body: "{{reason}}" },
    newDeal: { title: "ಹೊಸ ಡೀಲ್ ಪ್ರಕಟಿಸಲಾಗಿದೆ", body: "{{title}}" },
    chatMessage: { title: "ಹೊಸ ಸಂದೇಶ · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "ಪಾವತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ", body: '{{buyer}} "{{title}}"ಗಾಗಿ ಪಾವತಿಸಿದ್ದಾರೆ. ಡೆಲಿವರಿ ದೃಢೀಕರಿಸುವವರೆಗೆ ಪಾವತಿಯನ್ನು ತಡೆಹಿಡಿಯಲಾಗಿದೆ.' },
    dealCompleted: { title: "ಡೀಲ್ ಪೂರ್ಣಗೊಂಡಿದೆ", body: 'ಮಾರಾಟಗಾರರು "{{title}}" ಪೂರ್ಣಗೊಂಡಿದೆ ಎಂದು ಗುರುತಿಸಿದ್ದಾರೆ. ಶೀಘ್ರದಲ್ಲೇ ಕಳುಹಿಸಲಾಗುವುದು.' },
    priceDropped: { title: "ಬೆಲೆ ಇಳಿದಿದೆ!", body: '"{{title}}"ಗೆ ಇನ್ನಷ್ಟು ಖರೀದಿದಾರರು ಸೇರಿದ್ದಾರೆ - ಗುಂಪು ಬೆಲೆ ಇಳಿದಿದ್ದರಿಂದ ₹{{amount}} ನಿಮಗೆ ಹಿಂತಿರುಗಿಸಲಾಗಿದೆ.' },
    dealEndedBySeller: { title: "ಡೀಲ್ ಮುಗಿದಿದೆ", body: 'ಸಾಕಷ್ಟು ಖರೀದಿದಾರರು ಸೇರುವ ಮೊದಲೇ ಮಾರಾಟಗಾರರು "{{title}}" ಅನ್ನು ಮುಗಿಸಿದ್ದಾರೆ.' },
    refunded: { title: "ಪಾವತಿ ಹಿಂತಿರುಗಿಸಲಾಗಿದೆ", body: '"{{title}}"ಗಾಗಿ ತಡೆಹಿಡಿದ ನಿಮ್ಮ ಪಾವತಿಯನ್ನು ನಿಮಗೆ ಹಿಂತಿರುಗಿಸಲಾಗಿದೆ.' },
    dispatched: { title: "ನಿಮ್ಮ ಆರ್ಡರ್ ದಾರಿಯಲ್ಲಿದೆ!", body: "{{title}} ಕಳುಹಿಸಲಾಗಿದೆ. ಡೆಲಿವರಿ ದೃಢೀಕರಣ ಕೋಡ್ ನೋಡಲು ಆ್ಯಪ್ ತೆರೆಯಿರಿ." },
    deliveryConfirmed: { title: "ಡೆಲಿವರಿ ದೃಢೀಕರಿಸಲಾಗಿದೆ", body: "{{buyer}} {{title}} ಡೆಲಿವರಿಯನ್ನು ದೃಢೀಕರಿಸಿದ್ದಾರೆ." },
    allDelivered: { title: "ಎಲ್ಲಾ ಆರ್ಡರ್‌ಗಳು ಡೆಲಿವರಿ ಆಗಿವೆ", body: "{{title}}ಗೆ ಸೇರಿದ ಎಲ್ಲಾ ಖರೀದಿದಾರರು ಡೆಲಿವರಿಯನ್ನು ದೃಢೀಕರಿಸಿದ್ದಾರೆ." },
    pickupConfirmed: { title: "ಪಿಕಪ್ ದೃಢೀಕರಿಸಲಾಗಿದೆ", body: '"{{title}}"ಗಾಗಿ ನಿಮ್ಮ ಪಿಕಪ್ ಅನ್ನು ಮಾರಾಟಗಾರರು ದೃಢೀಕರಿಸಿದ್ದಾರೆ.' },
    deliveryMarkedBySeller: { title: "ಡೆಲಿವರಿ ಪೂರ್ಣ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ", body: '"{{title}}"ಗಾಗಿ ನಿಮ್ಮ ಆರ್ಡರ್ ಡೆಲಿವರಿ ಆಗಿದೆ ಎಂದು ಮಾರಾಟಗಾರರು ಗುರುತಿಸಿದ್ದಾರೆ.' },
  },
  bn: {
    someBuyer: "একজন ক্রেতা",
    yourDeal: "আপনার ডিল",
    dealExpiredShortfall: { title: "ডিলের মেয়াদ শেষ", body: 'সব ক্রেতার পেমেন্টের আগেই "{{title}}"-এর মেয়াদ শেষ হয়েছে। এটি মেয়াদোত্তীর্ণ তালিকায় গেছে।' },
    dealExpiredQuorum: { title: "ডিলের মেয়াদ শেষ", body: 'যথেষ্ট ক্রেতা ছাড়াই "{{title}}"-এর মেয়াদ শেষ হয়েছে। এটি মেয়াদোত্তীর্ণ তালিকায় গেছে।' },
    refundedExpired: { title: "পেমেন্ট ফেরত", body: 'ডিলের মেয়াদ শেষ হওয়ায় "{{title}}"-এর জন্য আটকে রাখা আপনার পেমেন্ট ফেরত দেওয়া হয়েছে।' },
    accountApprovedSeller: { title: "অ্যাকাউন্ট অনুমোদিত", body: "আপনার বিক্রেতা অ্যাকাউন্ট অনুমোদিত হয়েছে।" },
    accountApproved: { title: "অ্যাকাউন্ট অনুমোদিত", body: "আপনার অ্যাকাউন্ট অনুমোদিত হয়েছে।" },
    accountRejected: { title: "অ্যাকাউন্ট প্রত্যাখ্যাত", body: "অ্যাডমিন আপনার অ্যাকাউন্টের অনুরোধ প্রত্যাখ্যান করেছেন।" },
    accountRejectedReason: { title: "অ্যাকাউন্ট প্রত্যাখ্যাত", body: "{{reason}}" },
    dealApproved: { title: "ডিল অনুমোদিত", body: "{{title}}" },
    dealRejected: { title: "ডিল প্রত্যাখ্যাত", body: "অ্যাডমিন আপনার ডিল প্রত্যাখ্যান করেছেন" },
    dealRejectedReason: { title: "ডিল প্রত্যাখ্যাত", body: "{{reason}}" },
    newDeal: { title: "নতুন ডিল প্রকাশিত", body: "{{title}}" },
    chatMessage: { title: "নতুন বার্তা · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "পেমেন্ট পাওয়া গেছে", body: '{{buyer}} "{{title}}"-এর জন্য পেমেন্ট করেছেন। ডেলিভারি নিশ্চিত না হওয়া পর্যন্ত পেমেন্ট আটকে থাকবে।' },
    dealCompleted: { title: "ডিল সম্পন্ন", body: 'বিক্রেতা "{{title}}" সম্পন্ন হিসেবে চিহ্নিত করেছেন। শীঘ্রই পাঠানো হবে।' },
    priceDropped: { title: "দাম কমেছে!", body: '"{{title}}"-এ আরও ক্রেতা যোগ দিয়েছেন - গ্রুপের দাম কমায় ₹{{amount}} আপনাকে ফেরত দেওয়া হয়েছে।' },
    dealEndedBySeller: { title: "ডিল শেষ", body: 'যথেষ্ট ক্রেতা হওয়ার আগেই বিক্রেতা "{{title}}" শেষ করেছেন।' },
    refunded: { title: "পেমেন্ট ফেরত", body: '"{{title}}"-এর জন্য আটকে রাখা আপনার পেমেন্ট ফেরত দেওয়া হয়েছে।' },
    dispatched: { title: "আপনার অর্ডার পথে!", body: "{{title}} পাঠানো হয়েছে। ডেলিভারি নিশ্চিতকরণ কোড দেখতে অ্যাপ খুলুন।" },
    deliveryConfirmed: { title: "ডেলিভারি নিশ্চিত", body: "{{buyer}} {{title}}-এর ডেলিভারি নিশ্চিত করেছেন।" },
    allDelivered: { title: "সব অর্ডার ডেলিভারি হয়েছে", body: "{{title}}-এর সব ক্রেতা ডেলিভারি নিশ্চিত করেছেন।" },
    pickupConfirmed: { title: "পিকআপ নিশ্চিত", body: 'বিক্রেতা "{{title}}"-এর জন্য আপনার পিকআপ নিশ্চিত করেছেন।' },
    deliveryMarkedBySeller: { title: "ডেলিভারি সম্পন্ন চিহ্নিত", body: 'বিক্রেতা "{{title}}"-এর আপনার অর্ডার ডেলিভারি হয়েছে বলে চিহ্নিত করেছেন।' },
  },
  gu: {
    someBuyer: "એક ખરીદનાર",
    yourDeal: "તમારી ડીલ",
    dealExpiredShortfall: { title: "ડીલ પૂરી થઈ", body: '"{{title}}" બધા ખરીદનારની ચુકવણી પહેલાં પૂરી થઈ. તેને સમાપ્તમાં ખસેડી છે.' },
    dealExpiredQuorum: { title: "ડીલ પૂરી થઈ", body: '"{{title}}" પૂરતા ખરીદનાર વિના પૂરી થઈ. તેને સમાપ્તમાં ખસેડી છે.' },
    refundedExpired: { title: "ચુકવણી પાછી", body: 'ડીલ પૂરી થવાથી "{{title}}" માટે રોકાયેલી તમારી ચુકવણી પાછી આપી છે.' },
    accountApprovedSeller: { title: "ખાતું મંજૂર", body: "તમારું વિક્રેતા ખાતું મંજૂર થયું છે." },
    accountApproved: { title: "ખાતું મંજૂર", body: "તમારું ખાતું મંજૂર થયું છે." },
    accountRejected: { title: "ખાતું નકારાયું", body: "ઍડમિને તમારી ખાતાની વિનંતી નકારી." },
    accountRejectedReason: { title: "ખાતું નકારાયું", body: "{{reason}}" },
    dealApproved: { title: "ડીલ મંજૂર", body: "{{title}}" },
    dealRejected: { title: "ડીલ નકારાઈ", body: "ઍડમિને તમારી ડીલ નકારી" },
    dealRejectedReason: { title: "ડીલ નકારાઈ", body: "{{reason}}" },
    newDeal: { title: "નવી ડીલ પ્રકાશિત", body: "{{title}}" },
    chatMessage: { title: "નવો સંદેશ · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "ચુકવણી મળી", body: '{{buyer}} એ "{{title}}" માટે ચુકવણી કરી. ડિલિવરીની પુષ્ટિ થાય ત્યાં સુધી ચુકવણી રોકાયેલી છે.' },
    dealCompleted: { title: "ડીલ પૂર્ણ", body: 'વિક્રેતાએ "{{title}}" પૂર્ણ તરીકે ચિહ્નિત કરી. તે જલ્દી મોકલાશે.' },
    priceDropped: { title: "કિંમત ઘટી!", body: '"{{title}}" માં વધુ ખરીદનાર જોડાયા - ગ્રુપ કિંમત ઘટતાં ₹{{amount}} તમને પાછા આપ્યા.' },
    dealEndedBySeller: { title: "ડીલ બંધ થઈ", body: 'પૂરતા ખરીદનાર જોડાય તે પહેલાં વિક્રેતાએ "{{title}}" બંધ કરી.' },
    refunded: { title: "ચુકવણી પાછી", body: '"{{title}}" માટે રોકાયેલી તમારી ચુકવણી પાછી આપી છે.' },
    dispatched: { title: "તમારો ઓર્ડર રસ્તામાં છે!", body: "{{title}} મોકલાઈ છે. ડિલિવરી પુષ્ટિ કોડ જોવા ઍપ ખોલો." },
    deliveryConfirmed: { title: "ડિલિવરી પાકી", body: "{{buyer}} એ {{title}} ની ડિલિવરીની પુષ્ટિ કરી." },
    allDelivered: { title: "બધા ઓર્ડર ડિલિવર", body: "{{title}} ના બધા ખરીદનારે ડિલિવરીની પુષ્ટિ કરી છે." },
    pickupConfirmed: { title: "પિકઅપ પાકું", body: 'વિક્રેતાએ "{{title}}" માટે તમારું પિકઅપ પાકું કર્યું છે.' },
    deliveryMarkedBySeller: { title: "ડિલિવરી પૂર્ણ ચિહ્નિત", body: 'વિક્રેતાએ "{{title}}" નો તમારો ઓર્ડર ડિલિવર થયો તરીકે ચિહ્નિત કર્યો.' },
  },
  ml: {
    someBuyer: "ഒരു വാങ്ങുന്നയാൾ",
    yourDeal: "നിങ്ങളുടെ ഡീൽ",
    dealExpiredShortfall: { title: "ഡീൽ കാലാവധി കഴിഞ്ഞു", body: 'എല്ലാ വാങ്ങുന്നവരും പണമടയ്ക്കും മുമ്പ് "{{title}}" കാലാവധി കഴിഞ്ഞു. ഇത് കാലാവധി കഴിഞ്ഞവയിലേക്ക് മാറ്റി.' },
    dealExpiredQuorum: { title: "ഡീൽ കാലാവധി കഴിഞ്ഞു", body: 'മതിയായ വാങ്ങുന്നവരില്ലാതെ "{{title}}" കാലാവധി കഴിഞ്ഞു. ഇത് കാലാവധി കഴിഞ്ഞവയിലേക്ക് മാറ്റി.' },
    refundedExpired: { title: "പണം തിരികെ നൽകി", body: 'ഡീൽ കാലാവധി കഴിഞ്ഞതിനാൽ "{{title}}" നായി തടഞ്ഞുവച്ച നിങ്ങളുടെ പണം തിരികെ നൽകി.' },
    accountApprovedSeller: { title: "അക്കൗണ്ട് അംഗീകരിച്ചു", body: "നിങ്ങളുടെ വിൽപ്പനക്കാരൻ അക്കൗണ്ട് അംഗീകരിച്ചു." },
    accountApproved: { title: "അക്കൗണ്ട് അംഗീകരിച്ചു", body: "നിങ്ങളുടെ അക്കൗണ്ട് അംഗീകരിച്ചു." },
    accountRejected: { title: "അക്കൗണ്ട് നിരസിച്ചു", body: "നിങ്ങളുടെ അക്കൗണ്ട് അഭ്യർത്ഥന അഡ്മിൻ നിരസിച്ചു." },
    accountRejectedReason: { title: "അക്കൗണ്ട് നിരസിച്ചു", body: "{{reason}}" },
    dealApproved: { title: "ഡീൽ അംഗീകരിച്ചു", body: "{{title}}" },
    dealRejected: { title: "ഡീൽ നിരസിച്ചു", body: "നിങ്ങളുടെ ഡീൽ അഡ്മിൻ നിരസിച്ചു" },
    dealRejectedReason: { title: "ഡീൽ നിരസിച്ചു", body: "{{reason}}" },
    newDeal: { title: "പുതിയ ഡീൽ പ്രസിദ്ധീകരിച്ചു", body: "{{title}}" },
    chatMessage: { title: "പുതിയ സന്ദേശം · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "പണം ലഭിച്ചു", body: '{{buyer}} "{{title}}" നായി പണമടച്ചു. ഡെലിവറി സ്ഥിരീകരിക്കും വരെ പണം തടഞ്ഞുവയ്ക്കും.' },
    dealCompleted: { title: "ഡീൽ പൂർത്തിയായി", body: 'വിൽപ്പനക്കാരൻ "{{title}}" പൂർത്തിയായതായി അടയാളപ്പെടുത്തി. ഉടൻ അയയ്ക്കും.' },
    priceDropped: { title: "വില കുറഞ്ഞു!", body: '"{{title}}" ൽ കൂടുതൽ പേർ ചേർന്നു - ഗ്രൂപ്പ് വില കുറഞ്ഞതിനാൽ ₹{{amount}} നിങ്ങൾക്ക് തിരികെ നൽകി.' },
    dealEndedBySeller: { title: "ഡീൽ അവസാനിച്ചു", body: 'മതിയായ വാങ്ങുന്നവർ ചേരും മുമ്പ് വിൽപ്പനക്കാരൻ "{{title}}" അവസാനിപ്പിച്ചു.' },
    refunded: { title: "പണം തിരികെ നൽകി", body: '"{{title}}" നായി തടഞ്ഞുവച്ച നിങ്ങളുടെ പണം തിരികെ നൽകി.' },
    dispatched: { title: "നിങ്ങളുടെ ഓർഡർ വഴിയിലാണ്!", body: "{{title}} അയച്ചു. ഡെലിവറി സ്ഥിരീകരണ കോഡ് കാണാൻ ആപ്പ് തുറക്കുക." },
    deliveryConfirmed: { title: "ഡെലിവറി സ്ഥിരീകരിച്ചു", body: "{{buyer}} {{title}} ന്റെ ഡെലിവറി സ്ഥിരീകരിച്ചു." },
    allDelivered: { title: "എല്ലാ ഓർഡറുകളും ഡെലിവർ ചെയ്തു", body: "{{title}} ൽ ചേർന്ന എല്ലാവരും ഡെലിവറി സ്ഥിരീകരിച്ചു." },
    pickupConfirmed: { title: "പിക്കപ്പ് സ്ഥിരീകരിച്ചു", body: '"{{title}}" നായുള്ള നിങ്ങളുടെ പിക്കപ്പ് വിൽപ്പനക്കാരൻ സ്ഥിരീകരിച്ചു.' },
    deliveryMarkedBySeller: { title: "ഡെലിവറി പൂർത്തിയായതായി അടയാളപ്പെടുത്തി", body: '"{{title}}" നായുള്ള നിങ്ങളുടെ ഓർഡർ ഡെലിവർ ചെയ്തതായി വിൽപ്പനക്കാരൻ അടയാളപ്പെടുത്തി.' },
  },
  pa: {
    someBuyer: "ਇੱਕ ਖਰੀਦਦਾਰ",
    yourDeal: "ਤੁਹਾਡੀ ਡੀਲ",
    dealExpiredShortfall: { title: "ਡੀਲ ਖਤਮ", body: '"{{title}}" ਸਾਰੇ ਖਰੀਦਦਾਰਾਂ ਦੇ ਭੁਗਤਾਨ ਤੋਂ ਪਹਿਲਾਂ ਖਤਮ ਹੋ ਗਈ। ਇਸਨੂੰ ਖਤਮ ਵਿੱਚ ਭੇਜ ਦਿੱਤਾ ਗਿਆ।' },
    dealExpiredQuorum: { title: "ਡੀਲ ਖਤਮ", body: '"{{title}}" ਲੋੜੀਂਦੇ ਖਰੀਦਦਾਰਾਂ ਤੋਂ ਬਿਨਾਂ ਖਤਮ ਹੋ ਗਈ। ਇਸਨੂੰ ਖਤਮ ਵਿੱਚ ਭੇਜ ਦਿੱਤਾ ਗਿਆ।' },
    refundedExpired: { title: "ਭੁਗਤਾਨ ਵਾਪਸ", body: 'ਡੀਲ ਖਤਮ ਹੋਣ ਕਾਰਨ "{{title}}" ਲਈ ਰੋਕਿਆ ਤੁਹਾਡਾ ਭੁਗਤਾਨ ਵਾਪਸ ਕਰ ਦਿੱਤਾ ਗਿਆ।' },
    accountApprovedSeller: { title: "ਖਾਤਾ ਮਨਜ਼ੂਰ", body: "ਤੁਹਾਡਾ ਵਿਕਰੇਤਾ ਖਾਤਾ ਮਨਜ਼ੂਰ ਹੋ ਗਿਆ ਹੈ।" },
    accountApproved: { title: "ਖਾਤਾ ਮਨਜ਼ੂਰ", body: "ਤੁਹਾਡਾ ਖਾਤਾ ਮਨਜ਼ੂਰ ਹੋ ਗਿਆ ਹੈ।" },
    accountRejected: { title: "ਖਾਤਾ ਰੱਦ", body: "ਐਡਮਿਨ ਨੇ ਤੁਹਾਡੀ ਖਾਤੇ ਦੀ ਬੇਨਤੀ ਰੱਦ ਕਰ ਦਿੱਤੀ।" },
    accountRejectedReason: { title: "ਖਾਤਾ ਰੱਦ", body: "{{reason}}" },
    dealApproved: { title: "ਡੀਲ ਮਨਜ਼ੂਰ", body: "{{title}}" },
    dealRejected: { title: "ਡੀਲ ਰੱਦ", body: "ਐਡਮਿਨ ਨੇ ਤੁਹਾਡੀ ਡੀਲ ਰੱਦ ਕਰ ਦਿੱਤੀ" },
    dealRejectedReason: { title: "ਡੀਲ ਰੱਦ", body: "{{reason}}" },
    newDeal: { title: "ਨਵੀਂ ਡੀਲ ਪ੍ਰਕਾਸ਼ਿਤ", body: "{{title}}" },
    chatMessage: { title: "ਨਵਾਂ ਸੁਨੇਹਾ · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "ਭੁਗਤਾਨ ਮਿਲਿਆ", body: '{{buyer}} ਨੇ "{{title}}" ਲਈ ਭੁਗਤਾਨ ਕੀਤਾ। ਡਿਲੀਵਰੀ ਪੱਕੀ ਹੋਣ ਤੱਕ ਭੁਗਤਾਨ ਰੋਕਿਆ ਗਿਆ ਹੈ।' },
    dealCompleted: { title: "ਡੀਲ ਪੂਰੀ", body: 'ਵਿਕਰੇਤਾ ਨੇ "{{title}}" ਨੂੰ ਪੂਰੀ ਦੱਸਿਆ। ਇਹ ਜਲਦੀ ਭੇਜੀ ਜਾਵੇਗੀ।' },
    priceDropped: { title: "ਕੀਮਤ ਘਟੀ!", body: '"{{title}}" ਵਿੱਚ ਹੋਰ ਖਰੀਦਦਾਰ ਜੁੜੇ - ਗਰੁੱਪ ਕੀਮਤ ਘਟਣ ਨਾਲ ₹{{amount}} ਤੁਹਾਨੂੰ ਵਾਪਸ ਕੀਤੇ ਗਏ।' },
    dealEndedBySeller: { title: "ਡੀਲ ਬੰਦ", body: 'ਲੋੜੀਂਦੇ ਖਰੀਦਦਾਰ ਜੁੜਨ ਤੋਂ ਪਹਿਲਾਂ ਵਿਕਰੇਤਾ ਨੇ "{{title}}" ਬੰਦ ਕਰ ਦਿੱਤੀ।' },
    refunded: { title: "ਭੁਗਤਾਨ ਵਾਪਸ", body: '"{{title}}" ਲਈ ਰੋਕਿਆ ਤੁਹਾਡਾ ਭੁਗਤਾਨ ਵਾਪਸ ਕਰ ਦਿੱਤਾ ਗਿਆ।' },
    dispatched: { title: "ਤੁਹਾਡਾ ਆਰਡਰ ਰਸਤੇ ਵਿੱਚ ਹੈ!", body: "{{title}} ਭੇਜ ਦਿੱਤੀ ਗਈ ਹੈ। ਡਿਲੀਵਰੀ ਪੁਸ਼ਟੀ ਕੋਡ ਵੇਖਣ ਲਈ ਐਪ ਖੋਲ੍ਹੋ।" },
    deliveryConfirmed: { title: "ਡਿਲੀਵਰੀ ਪੱਕੀ", body: "{{buyer}} ਨੇ {{title}} ਦੀ ਡਿਲੀਵਰੀ ਪੱਕੀ ਕੀਤੀ।" },
    allDelivered: { title: "ਸਾਰੇ ਆਰਡਰ ਡਿਲੀਵਰ", body: "{{title}} ਦੇ ਸਾਰੇ ਖਰੀਦਦਾਰਾਂ ਨੇ ਡਿਲੀਵਰੀ ਪੱਕੀ ਕਰ ਦਿੱਤੀ ਹੈ।" },
    pickupConfirmed: { title: "ਪਿਕਅੱਪ ਪੱਕਾ", body: 'ਵਿਕਰੇਤਾ ਨੇ "{{title}}" ਲਈ ਤੁਹਾਡਾ ਪਿਕਅੱਪ ਪੱਕਾ ਕਰ ਦਿੱਤਾ ਹੈ।' },
    deliveryMarkedBySeller: { title: "ਡਿਲੀਵਰੀ ਪੂਰੀ ਦੱਸੀ ਗਈ", body: 'ਵਿਕਰੇਤਾ ਨੇ "{{title}}" ਦਾ ਤੁਹਾਡਾ ਆਰਡਰ ਡਿਲੀਵਰ ਦੱਸਿਆ ਹੈ।' },
  },
  or: {
    someBuyer: "ଜଣେ କ୍ରେତା",
    yourDeal: "ଆପଣଙ୍କ ଡିଲ",
    dealExpiredShortfall: { title: "ଡିଲ ମିଆଦ ଶେଷ", body: 'ସବୁ କ୍ରେତା ଦେୟ ଦେବା ପୂର୍ବରୁ "{{title}}"ର ମିଆଦ ଶେଷ ହେଲା। ଏହାକୁ ମିଆଦ ଶେଷ ତାଲିକାକୁ ନିଆଗଲା।' },
    dealExpiredQuorum: { title: "ଡିଲ ମିଆଦ ଶେଷ", body: 'ଯଥେଷ୍ଟ କ୍ରେତା ବିନା "{{title}}"ର ମିଆଦ ଶେଷ ହେଲା। ଏହାକୁ ମିଆଦ ଶେଷ ତାଲିକାକୁ ନିଆଗଲା।' },
    refundedExpired: { title: "ଦେୟ ଫେରସ୍ତ", body: 'ଡିଲର ମିଆଦ ଶେଷ ହେବାରୁ "{{title}}" ପାଇଁ ଅଟକାଯାଇଥିବା ଆପଣଙ୍କ ଦେୟ ଫେରସ୍ତ ହେଲା।' },
    accountApprovedSeller: { title: "ଆକାଉଣ୍ଟ ଅନୁମୋଦିତ", body: "ଆପଣଙ୍କ ବିକ୍ରେତା ଆକାଉଣ୍ଟ ଅନୁମୋଦିତ ହେଲା।" },
    accountApproved: { title: "ଆକାଉଣ୍ଟ ଅନୁମୋଦିତ", body: "ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ଅନୁମୋଦିତ ହେଲା।" },
    accountRejected: { title: "ଆକାଉଣ୍ଟ ପ୍ରତ୍ୟାଖ୍ୟାତ", body: "ଆଡମିନ ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ଅନୁରୋଧ ପ୍ରତ୍ୟାଖ୍ୟାନ କଲେ।" },
    accountRejectedReason: { title: "ଆକାଉଣ୍ଟ ପ୍ରତ୍ୟାଖ୍ୟାତ", body: "{{reason}}" },
    dealApproved: { title: "ଡିଲ ଅନୁମୋଦିତ", body: "{{title}}" },
    dealRejected: { title: "ଡିଲ ପ୍ରତ୍ୟାଖ୍ୟାତ", body: "ଆଡମିନ ଆପଣଙ୍କ ଡିଲ ପ୍ରତ୍ୟାଖ୍ୟାନ କଲେ" },
    dealRejectedReason: { title: "ଡିଲ ପ୍ରତ୍ୟାଖ୍ୟାତ", body: "{{reason}}" },
    newDeal: { title: "ନୂଆ ଡିଲ ପ୍ରକାଶିତ", body: "{{title}}" },
    chatMessage: { title: "ନୂଆ ବାର୍ତ୍ତା · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "ଦେୟ ମିଳିଲା", body: '{{buyer}} "{{title}}" ପାଇଁ ଦେୟ ଦେଲେ। ଡେଲିଭରି ନିଶ୍ଚିତ ହେବା ପର୍ଯ୍ୟନ୍ତ ଦେୟ ଅଟକାଯାଇଛି।' },
    dealCompleted: { title: "ଡିଲ ସମ୍ପୂର୍ଣ୍ଣ", body: 'ବିକ୍ରେତା "{{title}}"କୁ ସମ୍ପୂର୍ଣ୍ଣ ବୋଲି ଚିହ୍ନିତ କଲେ। ଶୀଘ୍ର ପଠାଯିବ।' },
    priceDropped: { title: "ଦାମ କମିଲା!", body: '"{{title}}"ରେ ଅଧିକ କ୍ରେତା ଯୋଗ ଦେଲେ - ଗ୍ରୁପ ଦାମ କମିବାରୁ ₹{{amount}} ଆପଣଙ୍କୁ ଫେରସ୍ତ ହେଲା।' },
    dealEndedBySeller: { title: "ଡିଲ ଶେଷ", body: 'ଯଥେଷ୍ଟ କ୍ରେତା ଯୋଗ ଦେବା ପୂର୍ବରୁ ବିକ୍ରେତା "{{title}}" ଶେଷ କଲେ।' },
    refunded: { title: "ଦେୟ ଫେରସ୍ତ", body: '"{{title}}" ପାଇଁ ଅଟକାଯାଇଥିବା ଆପଣଙ୍କ ଦେୟ ଫେରସ୍ତ ହେଲା।' },
    dispatched: { title: "ଆପଣଙ୍କ ଅର୍ଡର ବାଟରେ ଅଛି!", body: "{{title}} ପଠାଗଲା। ଡେଲିଭରି ନିଶ୍ଚିତକରଣ କୋଡ ଦେଖିବାକୁ ଆପ ଖୋଲନ୍ତୁ।" },
    deliveryConfirmed: { title: "ଡେଲିଭରି ନିଶ୍ଚିତ", body: "{{buyer}} {{title}}ର ଡେଲିଭରି ନିଶ୍ଚିତ କଲେ।" },
    allDelivered: { title: "ସବୁ ଅର୍ଡର ଡେଲିଭରି ହେଲା", body: "{{title}}ର ସବୁ କ୍ରେତା ଡେଲିଭରି ନିଶ୍ଚିତ କରିଛନ୍ତି।" },
    pickupConfirmed: { title: "ପିକଅପ ନିଶ୍ଚିତ", body: 'ବିକ୍ରେତା "{{title}}" ପାଇଁ ଆପଣଙ୍କ ପିକଅପ ନିଶ୍ଚିତ କଲେ।' },
    deliveryMarkedBySeller: { title: "ଡେଲିଭରି ସମ୍ପୂର୍ଣ୍ଣ ଚିହ୍ନିତ", body: 'ବିକ୍ରେତା "{{title}}"ର ଆପଣଙ୍କ ଅର୍ଡର ଡେଲିଭରି ହେଲା ବୋଲି ଚିହ୍ନିତ କଲେ।' },
  },
  as: {
    someBuyer: "এজন ক্ৰেতা",
    yourDeal: "আপোনাৰ ডিল",
    dealExpiredShortfall: { title: "ডিলৰ ম্যাদ উকলিল", body: 'সকলো ক্ৰেতাই পৰিশোধ কৰাৰ আগতে "{{title}}"ৰ ম্যাদ উকলিল। ইয়াক ম্যাদ উকলা তালিকালৈ নিয়া হ\'ল।' },
    dealExpiredQuorum: { title: "ডিলৰ ম্যাদ উকলিল", body: 'যথেষ্ট ক্ৰেতা নোহোৱাকৈ "{{title}}"ৰ ম্যাদ উকলিল। ইয়াক ম্যাদ উকলা তালিকালৈ নিয়া হ\'ল।' },
    refundedExpired: { title: "পৰিশোধ ঘূৰাই দিয়া হ'ল", body: 'ডিলৰ ম্যাদ উকলাৰ বাবে "{{title}}"ৰ বাবে ৰখা আপোনাৰ পৰিশোধ ঘূৰাই দিয়া হ\'ল।' },
    accountApprovedSeller: { title: "একাউণ্ট অনুমোদিত", body: "আপোনাৰ বিক্ৰেতা একাউণ্ট অনুমোদিত হ'ল।" },
    accountApproved: { title: "একাউণ্ট অনুমোদিত", body: "আপোনাৰ একাউণ্ট অনুমোদিত হ'ল।" },
    accountRejected: { title: "একাউণ্ট নাকচ", body: "এডমিনে আপোনাৰ একাউণ্টৰ অনুৰোধ নাকচ কৰিলে।" },
    accountRejectedReason: { title: "একাউণ্ট নাকচ", body: "{{reason}}" },
    dealApproved: { title: "ডিল অনুমোদিত", body: "{{title}}" },
    dealRejected: { title: "ডিল নাকচ", body: "এডমিনে আপোনাৰ ডিল নাকচ কৰিলে" },
    dealRejectedReason: { title: "ডিল নাকচ", body: "{{reason}}" },
    newDeal: { title: "নতুন ডিল প্ৰকাশিত", body: "{{title}}" },
    chatMessage: { title: "নতুন বাৰ্তা · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "পৰিশোধ পোৱা গ'ল", body: '"{{title}}"ৰ বাবে {{buyer}}ৰ পৰা পৰিশোধ পোৱা গ\x27ল। ডেলিভাৰী নিশ্চিত নোহোৱালৈকে পৰিশোধ ৰখা হৈছে।' },
    dealCompleted: { title: "ডিল সম্পূৰ্ণ", body: 'বিক্ৰেতাই "{{title}}" সম্পূৰ্ণ বুলি চিহ্নিত কৰিলে। সোনকালে পঠোৱা হ\'ব।' },
    priceDropped: { title: "দাম কমিল!", body: '"{{title}}"ত আৰু ক্ৰেতা যোগ দিলে - গ্ৰুপৰ দাম কমাত ₹{{amount}} আপোনাক ঘূৰাই দিয়া হ\'ল।' },
    dealEndedBySeller: { title: "ডিল শেষ", body: 'যথেষ্ট ক্ৰেতা যোগ দিয়াৰ আগতে বিক্ৰেতাই "{{title}}" শেষ কৰিলে।' },
    refunded: { title: "পৰিশোধ ঘূৰাই দিয়া হ'ল", body: '"{{title}}"ৰ বাবে ৰখা আপোনাৰ পৰিশোধ ঘূৰাই দিয়া হ\'ল।' },
    dispatched: { title: "আপোনাৰ অৰ্ডাৰ বাটত আছে!", body: "{{title}} পঠোৱা হৈছে। ডেলিভাৰী নিশ্চিতকৰণ ক'ড চাবলৈ এপ খোলক।" },
    deliveryConfirmed: { title: "ডেলিভাৰী নিশ্চিত", body: "{{title}}ৰ ডেলিভাৰী {{buyer}}ৰ দ্বাৰা নিশ্চিত কৰা হ'ল।" },
    allDelivered: { title: "সকলো অৰ্ডাৰ ডেলিভাৰী হ'ল", body: "{{title}}ৰ সকলো ক্ৰেতাই ডেলিভাৰী নিশ্চিত কৰিছে।" },
    pickupConfirmed: { title: "পিকআপ নিশ্চিত", body: 'বিক্ৰেতাই "{{title}}"ৰ বাবে আপোনাৰ পিকআপ নিশ্চিত কৰিলে।' },
    deliveryMarkedBySeller: { title: "ডেলিভাৰী সম্পূৰ্ণ বুলি চিহ্নিত", body: 'বিক্ৰেতাই "{{title}}"ৰ আপোনাৰ অৰ্ডাৰ ডেলিভাৰী হ\'ল বুলি চিহ্নিত কৰিলে।' },
  },
  ur: {
    someBuyer: "ایک خریدار",
    yourDeal: "آپ کی ڈیل",
    dealExpiredShortfall: { title: "ڈیل ختم", body: '"{{title}}" تمام خریداروں کی ادائیگی سے پہلے ختم ہو گئی۔ اسے ختم شدہ میں منتقل کر دیا گیا۔' },
    dealExpiredQuorum: { title: "ڈیل ختم", body: '"{{title}}" کافی خریداروں کے بغیر ختم ہو گئی۔ اسے ختم شدہ میں منتقل کر دیا گیا۔' },
    refundedExpired: { title: "ادائیگی واپس", body: 'ڈیل ختم ہونے کی وجہ سے "{{title}}" کے لیے روکی گئی آپ کی ادائیگی واپس کر دی گئی۔' },
    accountApprovedSeller: { title: "اکاؤنٹ منظور", body: "آپ کا فروخت کنندہ اکاؤنٹ منظور ہو گیا ہے۔" },
    accountApproved: { title: "اکاؤنٹ منظور", body: "آپ کا اکاؤنٹ منظور ہو گیا ہے۔" },
    accountRejected: { title: "اکاؤنٹ مسترد", body: "ایڈمن نے آپ کی اکاؤنٹ کی درخواست مسترد کر دی۔" },
    accountRejectedReason: { title: "اکاؤنٹ مسترد", body: "{{reason}}" },
    dealApproved: { title: "ڈیل منظور", body: "{{title}}" },
    dealRejected: { title: "ڈیل مسترد", body: "ایڈمن نے آپ کی ڈیل مسترد کر دی" },
    dealRejectedReason: { title: "ڈیل مسترد", body: "{{reason}}" },
    newDeal: { title: "نئی ڈیل شائع ہوئی", body: "{{title}}" },
    chatMessage: { title: "نیا پیغام · {{title}}", body: "{{text}}" },
    paymentReceived: { title: "ادائیگی موصول", body: '{{buyer}} نے "{{title}}" کے لیے ادائیگی کی۔ ڈیلیوری کی تصدیق تک ادائیگی روکی گئی ہے۔' },
    dealCompleted: { title: "ڈیل مکمل", body: 'فروخت کنندہ نے "{{title}}" کو مکمل قرار دیا۔ یہ جلد بھیجی جائے گی۔' },
    priceDropped: { title: "قیمت کم ہو گئی!", body: '"{{title}}" میں مزید خریدار شامل ہوئے - گروپ قیمت کم ہونے پر ₹{{amount}} آپ کو واپس کیے گئے۔' },
    dealEndedBySeller: { title: "ڈیل بند", body: 'کافی خریدار شامل ہونے سے پہلے فروخت کنندہ نے "{{title}}" بند کر دی۔' },
    refunded: { title: "ادائیگی واپس", body: '"{{title}}" کے لیے روکی گئی آپ کی ادائیگی واپس کر دی گئی۔' },
    dispatched: { title: "آپ کا آرڈر راستے میں ہے!", body: "{{title}} بھیج دی گئی ہے۔ ڈیلیوری تصدیقی کوڈ دیکھنے کے لیے ایپ کھولیں۔" },
    deliveryConfirmed: { title: "ڈیلیوری کی تصدیق", body: "{{buyer}} نے {{title}} کی ڈیلیوری کی تصدیق کی۔" },
    allDelivered: { title: "تمام آرڈرز ڈیلیور", body: "{{title}} کے تمام خریداروں نے ڈیلیوری کی تصدیق کر دی ہے۔" },
    pickupConfirmed: { title: "پک اپ کی تصدیق", body: 'فروخت کنندہ نے "{{title}}" کے لیے آپ کے پک اپ کی تصدیق کر دی۔' },
    deliveryMarkedBySeller: { title: "ڈیلیوری مکمل قرار دی گئی", body: 'فروخت کنندہ نے "{{title}}" کا آپ کا آرڈر ڈیلیور قرار دیا۔' },
  },
};

function interpolate(template, vars) {
  return String(template).replace(/\{\{(\w+)\}\}/g, (match, name) =>
    vars[name] === undefined || vars[name] === null ? match : String(vars[name]),
  );
}

// message: { key, vars } - vars.title is the seller's deal title (translated
// here when dealId is known), vars.buyer a person's name (never translated;
// falls back to "A buyer" in the recipient's language).
async function renderNotification(message, preferredLanguage, dealId) {
  const lang = normalizeLanguage(preferredLanguage) || "en";
  const strings = TEMPLATES[lang] || TEMPLATES.en;
  const template = strings[message.key] || TEMPLATES.en[message.key];
  if (!template) throw new Error(`Unknown notification key: ${message.key}`);

  const vars = { ...(message.vars || {}) };
  if (vars.title) {
    vars.title = await translateDealText(dealId, "title", vars.title, lang, {
      waitMs: NOTIFICATION_TRANSLATION_WAIT_MS,
    });
  } else if ("title" in vars) {
    vars.title = strings.yourDeal;
  }
  if ("buyer" in vars && !vars.buyer) vars.buyer = strings.someBuyer;

  return {
    title: interpolate(template.title, vars),
    body: interpolate(template.body, vars),
  };
}

module.exports = { renderNotification, TEMPLATES };
